### ISSUE TITLE
topomlp

### ISSUE THREAD

**Issue by xiaonan12138** [Benson722/Learning-Notes#1]
hi,我发现你也在关注topomlp这个工作
我想和你交流一些可视化的问题，如果你方便可以和我这个邮箱联系1044773549@qq.com

**Comment by Benson722** [comment]
很抱歉现在才回复您的消息。

关于topomlp的可视化问题我也知之甚少，细节已记不太清了。您可以联系这篇论文的作者去了解详情，Good luck. :)
